---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-2
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-2
  namespace: mysql-2
spec:
  selector:
    matchLabels:
      app: mysql-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-2
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-2
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: ASjnfiuw!23
        ports:
        - containerPort: 3306
          name: mysql-2
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-anf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-anf
  namespace: mysql-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: netapp-anf-perf-standard
